---
name: Release Please

"on":
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - mods/**

concurrency:
  group: release-please
  cancel-in-progress: false

jobs:
  release-please:
    name: Release Please
    outputs:
      manifest: ${{ toJSON(steps.rp.outputs) }}
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        id: rp
        uses: googleapis/release-please-action@v4.1.3
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
  matrix:
    if: ${{ fromJSON(needs.release-please.outputs.manifest).releases_created == 'true' }}
    needs: [release-please]
    secrets: inherit
    strategy:
      matrix:
        path: ${{ fromJSON(fromJSON(needs.release-please.outputs.manifest).paths_released) }}
    uses: ./.github/workflows/build.yaml
    with:
      path: ${{ matrix.path }}
      manifest: ${{ needs.release-please.outputs.manifest }}